'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Download, Copy, CheckCircle2, XCircle, AlertTriangle, Info } from 'lucide-react';

interface SecurityReportProps {
  report: string;
  verdict?: 'approved' | 'rejected' | 'partial';
  vulnerabilitiesCount?: number;
  fixedCount?: number;
}

export default function SecurityReport({
  report,
  verdict,
  vulnerabilitiesCount = 0,
  fixedCount = 0,
}: SecurityReportProps) {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security-audit-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getVerdictInfo = () => {
    switch (verdict) {
      case 'approved':
        return {
          icon: <CheckCircle2 className="w-6 h-6" />,
          text: 'All Fixes Verified',
          color: 'text-agent-defender',
          bgColor: 'bg-agent-defender/10',
          borderColor: 'border-agent-defender/30',
        };
      case 'rejected':
        return {
          icon: <XCircle className="w-6 h-6" />,
          text: 'Vulnerabilities Remain',
          color: 'text-agent-attacker',
          bgColor: 'bg-agent-attacker/10',
          borderColor: 'border-agent-attacker/30',
        };
      case 'partial':
        return {
          icon: <AlertTriangle className="w-6 h-6" />,
          text: 'Partially Fixed',
          color: 'text-agent-arbiter',
          bgColor: 'bg-agent-arbiter/10',
          borderColor: 'border-agent-arbiter/30',
        };
      default:
        return {
          icon: <Info className="w-6 h-6" />,
          text: 'Audit Complete',
          color: 'text-agent-reporter',
          bgColor: 'bg-agent-reporter/10',
          borderColor: 'border-agent-reporter/30',
        };
    }
  };

  const verdictInfo = getVerdictInfo();

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-bg-secondary rounded-xl border border-border-default overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border-default bg-bg-tertiary/50">
        <div className="flex items-center gap-3">
          <span className="text-2xl">📋</span>
          <div>
            <h3 className="font-semibold text-agent-reporter">Security Audit Report</h3>
            <p className="text-xs text-text-secondary">Generated by Red Team Code Auditor</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg bg-bg-tertiary border border-border-default hover:border-agent-reporter transition-colors"
          >
            {copied ? (
              <>
                <CheckCircle2 className="w-3.5 h-3.5 text-agent-defender" />
                <span className="text-agent-defender">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy</span>
              </>
            )}
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs rounded-lg bg-agent-reporter text-white hover:bg-agent-reporter/90 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Verdict Banner */}
      {verdict && (
        <div
          className={`flex items-center justify-between px-4 py-3 border-b ${verdictInfo.borderColor} ${verdictInfo.bgColor}`}
        >
          <div className="flex items-center gap-3">
            <span className={verdictInfo.color}>{verdictInfo.icon}</span>
            <div>
              <p className={`font-semibold ${verdictInfo.color}`}>{verdictInfo.text}</p>
              <p className="text-xs text-text-secondary">
                {vulnerabilitiesCount} vulnerabilities found • {fixedCount} fixes verified
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Report Content */}
      <div className="p-4 max-h-[400px] overflow-y-auto">
        <div className="prose prose-invert prose-sm max-w-none">
          <pre className="whitespace-pre-wrap text-sm text-text-primary font-mono bg-bg-tertiary rounded-lg p-4 border border-border-default">
            {report}
          </pre>
        </div>
      </div>
    </motion.div>
  );
}
